A = 10
B = 20
IF A = 10 AND B = 20 THEN PRINT "INT AND INT: PASS" ELSE PRINT "INT AND INT: FAIL"

S$ = "Hello"
C = 5
IF S$ = "Hello" AND C = 5 THEN PRINT "STR AND INT: PASS" ELSE PRINT "STR AND INT: FAIL"
END
